<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerShbqQx2\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerShbqQx2/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerShbqQx2.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerShbqQx2\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerShbqQx2\srcApp_KernelProdContainer([
    'container.build_hash' => 'ShbqQx2',
    'container.build_id' => '3778e0a5',
    'container.build_time' => 1575891817,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerShbqQx2');
