<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.dU7J6TP' shared service.

return $this->privates['.service_locator.dU7J6TP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService.php', true],
    'repo' => ['privates', 'App\\Repository\\EventRepository', 'getEventRepositoryService.php', true],
], [
    'manager' => '?',
    'repo' => 'App\\Repository\\EventRepository',
]);
