<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentResolver\\ServiceValueResolver.php';

return $this->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\AdminController::DeleteEvent' => ['privates', '.service_locator.dU7J6TP', 'get_ServiceLocator_DU7J6TPService.php', true],
    'App\\Controller\\AdminController::createEvent' => ['privates', '.service_locator.LvxXihR', 'get_ServiceLocator_LvxXihRService.php', true],
    'App\\Controller\\AdminController::showEvents' => ['privates', '.service_locator.0xifNOT', 'get_ServiceLocator_0xifNOTService.php', true],
    'App\\Controller\\MMAsiteController::lesemploisdutempsmenu' => ['privates', '.service_locator.aZtBke8', 'get_ServiceLocator_AZtBke8Service.php', true],
    'App\\Controller\\MMAsiteController::showEdt' => ['privates', '.service_locator.aZtBke8', 'get_ServiceLocator_AZtBke8Service.php', true],
    'App\\Controller\\MMAsiteController::showEvent' => ['privates', '.service_locator.0xifNOT', 'get_ServiceLocator_0xifNOTService.php', true],
    'App\\Controller\\MMAsiteController::showEvents' => ['privates', '.service_locator.0xifNOT', 'get_ServiceLocator_0xifNOTService.php', true],
    'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
    'App\\Controller\\AdminController:DeleteEvent' => ['privates', '.service_locator.dU7J6TP', 'get_ServiceLocator_DU7J6TPService.php', true],
    'App\\Controller\\AdminController:createEvent' => ['privates', '.service_locator.LvxXihR', 'get_ServiceLocator_LvxXihRService.php', true],
    'App\\Controller\\AdminController:showEvents' => ['privates', '.service_locator.0xifNOT', 'get_ServiceLocator_0xifNOTService.php', true],
    'App\\Controller\\MMAsiteController:lesemploisdutempsmenu' => ['privates', '.service_locator.aZtBke8', 'get_ServiceLocator_AZtBke8Service.php', true],
    'App\\Controller\\MMAsiteController:showEdt' => ['privates', '.service_locator.aZtBke8', 'get_ServiceLocator_AZtBke8Service.php', true],
    'App\\Controller\\MMAsiteController:showEvent' => ['privates', '.service_locator.0xifNOT', 'get_ServiceLocator_0xifNOTService.php', true],
    'App\\Controller\\MMAsiteController:showEvents' => ['privates', '.service_locator.0xifNOT', 'get_ServiceLocator_0xifNOTService.php', true],
    'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
], [
    'App\\Controller\\AdminController::DeleteEvent' => '?',
    'App\\Controller\\AdminController::createEvent' => '?',
    'App\\Controller\\AdminController::showEvents' => '?',
    'App\\Controller\\MMAsiteController::lesemploisdutempsmenu' => '?',
    'App\\Controller\\MMAsiteController::showEdt' => '?',
    'App\\Controller\\MMAsiteController::showEvent' => '?',
    'App\\Controller\\MMAsiteController::showEvents' => '?',
    'App\\Controller\\SecurityController::login' => '?',
    'App\\Controller\\AdminController:DeleteEvent' => '?',
    'App\\Controller\\AdminController:createEvent' => '?',
    'App\\Controller\\AdminController:showEvents' => '?',
    'App\\Controller\\MMAsiteController:lesemploisdutempsmenu' => '?',
    'App\\Controller\\MMAsiteController:showEdt' => '?',
    'App\\Controller\\MMAsiteController:showEvent' => '?',
    'App\\Controller\\MMAsiteController:showEvents' => '?',
    'App\\Controller\\SecurityController:login' => '?',
]));
