<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Xmiscbh' shared service.

return $this->privates['.service_locator.Xmiscbh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'eventrepo' => ['privates', 'App\\Repository\\EventRepository', 'getEventRepositoryService.php', true],
    'repo' => ['privates', 'App\\Repository\\EmploisdutempsRepository', 'getEmploisdutempsRepositoryService.php', true],
], [
    'eventrepo' => 'App\\Repository\\EventRepository',
    'repo' => 'App\\Repository\\EmploisdutempsRepository',
]);
