<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTUjjzF7\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTUjjzF7/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTUjjzF7.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTUjjzF7\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerTUjjzF7\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'TUjjzF7',
    'container.build_id' => '061a6cb2',
    'container.build_time' => 1583568146,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTUjjzF7');
