<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJ8jtgZe\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJ8jtgZe/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJ8jtgZe.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJ8jtgZe\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerJ8jtgZe\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'J8jtgZe',
    'container.build_id' => '8d013587',
    'container.build_time' => 1579028704,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJ8jtgZe');
