<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Event extends \App\Entity\Event implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Event' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Event' . "\0" . 'nom', '' . "\0" . 'App\\Entity\\Event' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Event' . "\0" . 'date', '' . "\0" . 'App\\Entity\\Event' . "\0" . 'heure', '' . "\0" . 'App\\Entity\\Event' . "\0" . 'adresse', '' . "\0" . 'App\\Entity\\Event' . "\0" . 'imagecover', '' . "\0" . 'App\\Entity\\Event' . "\0" . 'prixadherent', '' . "\0" . 'App\\Entity\\Event' . "\0" . 'prixnonadherent'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Event' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Event' . "\0" . 'nom', '' . "\0" . 'App\\Entity\\Event' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Event' . "\0" . 'date', '' . "\0" . 'App\\Entity\\Event' . "\0" . 'heure', '' . "\0" . 'App\\Entity\\Event' . "\0" . 'adresse', '' . "\0" . 'App\\Entity\\Event' . "\0" . 'imagecover', '' . "\0" . 'App\\Entity\\Event' . "\0" . 'prixadherent', '' . "\0" . 'App\\Entity\\Event' . "\0" . 'prixnonadherent'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Event $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom(string $nom): \App\Entity\Event
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(string $description): \App\Entity\Event
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', []);

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate(\DateTimeInterface $date): \App\Entity\Event
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', [$date]);

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeure(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeure', []);

        return parent::getHeure();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeure(\DateTimeInterface $heure): \App\Entity\Event
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeure', [$heure]);

        return parent::setHeure($heure);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', []);

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse(string $adresse): \App\Entity\Event
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', [$adresse]);

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getImagecover(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImagecover', []);

        return parent::getImagecover();
    }

    /**
     * {@inheritDoc}
     */
    public function setImagecover(string $imagecover): \App\Entity\Event
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImagecover', [$imagecover]);

        return parent::setImagecover($imagecover);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrixadherent(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrixadherent', []);

        return parent::getPrixadherent();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrixadherent(float $prixadherent): \App\Entity\Event
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrixadherent', [$prixadherent]);

        return parent::setPrixadherent($prixadherent);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrixnonadherent(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrixnonadherent', []);

        return parent::getPrixnonadherent();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrixnonadherent(float $prixnonadherent): \App\Entity\Event
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrixnonadherent', [$prixnonadherent]);

        return parent::setPrixnonadherent($prixnonadherent);
    }

}
